--c1
SELECT * FROM SANPHAM,KHACHHANG
--c2
SELECT * FROM SANPHAM,KHACHHANG
--c3
UPDATE SANPHAM SET GIA =GIA/(100/5)+GIA
WHERE NUOCSX = N'Thai Lan'
--c4
UPDATE SANPHAM SET GIA =GIA/(100/5)+GIA
WHERE NUOCSX = N'Trung Quoc'
--c5
UPDATE KHACHHANG SET LOAIKH =N'VIP' 
WHERE (NGDK<cast('2011/1/1' as date) AND DOANHSO>=10000000) 
OR (NGDK>cast('2011/1/1' as date) AND DOANHSO >=2000000)

-------------Bài 3------------
--c1
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'TRUNG QUOC'
--c2
SELECT MASP, TENSP
FROM SANPHAM
WHERE DVT IN('CAY', 'QUYEN')
--c3
SELECT MASP,TENSP
FROM  SANPHAM
WHERE MASP LIKE 'B%01'
--c4
SELECT MASP,TENSP,NUOCSX
FROM SANPHAM
WHERE NUOCSX = 'TRUNG QUOC'
AND GIA BETWEEN 30000 AND 40000
--c5
SELECT MASP, TENSP, NUOCSX
FROM SANPHAM
WHERE (NUOCSX = 'TRUNG QUOC' OR NUOCSX = 'THAI LAN') AND GIA BETWEEN 30000 AND 40000
--c6
SELECT SOHD,TRIGIA
FROM  HOADON
WHERE NGHD=cast('2007/01/01' as date) OR NGHD=cast('2007/01/02' as date) 
--c7
SELECT SOHD,TRIGIA
FROM  HOADON
WHERE MONTH(NGHD)=1 AND YEAR(NGHD)=2007
ORDER BY  NGHD ASC,TRIGIA DESC
--c8
SELECT HOADON.MAKH,KHACHHANG.HOTEN
FROM  HOADON , KHACHHANG 
WHERE HOADON.MAKH=KHACHHANG.MAKH AND NGHD=cast('2007/01/01' as date) 
--c9
SELECT SOHD,TRIGIA
FROM  HOADON , NHANVIEN 
WHERE HOADON.MANV=NHANVIEN.MANV AND NGHD=cast('2006/10/28' as date)  AND HOTEN='Nguyen Van B' 
--c10
SELECT C
.MASP, TENSP
FROM  HOADON A, KHACHHANG B, CTHD C, SANPHAM D
WHERE A.MAKH=B.MAKH AND A.SOHD=C.SOHD AND C.MASP=D.MASP AND
  MONTH(NGHD)=10 AND YEAR(NGHD)=2006 AND HOTEN='Nguyen Van A'